FROM registry.access.redhat.com/ubi8/ubi-init

# registry.access.redhat.com/ubi8/ubi

#RUN yum -y install wget unzip

Workdir /usr/ibm
RUN yum -y install wget unzip \
  && wget http://engineering.asuscomm.com:8081/download/ELM-Web.zip \
  && unzip ELM-Web.zip \
  && ulimit -n 65536 \
  && ulimit -u 10000 \
  && mkdir /usr/ibm/im/repo \
  && cd /usr/ibm/im/repo \
  && wget http://engineering.asuscomm.com:8081/download/repo-7.0.2.zip \
  && unzip repo-7.0.2.zip \
  && cd /usr/ibm/im/linux.gtk.x86_64 \
  && ./installc -acceptLicense -showVerboseProgress -input silent-install-server2.xml --launcher.ini silent-install.ini \
  && rm -rf /usr/ibm \
  && chown -R 1001:0 /opt/IBM 

#Workdir /usr/ibm/im/repo
#RUN wget http://engineering.asuscomm.com:8081/download/repo-7.0.2.zip
#RUN unzip repo-7.0.2.zip
#Workdir /usr/ibm/im/linux.gtk.x86_64

# execute silent JAZZ install in standard directories
#RUN ./installc -acceptLicense -showVerboseProgress -input silent-install-server2.xml --launcher.ini silent-install.ini
#RUN rm -rf /usr/ibm
#RUN chown -R 1001:0 /opt/IBM
EXPOSE 9443
EXPOSE 9080
USER 1001
Workdir /opt/IBM/JazzTeamServer/server
#ENTRYPOINT ["/opt/IBM/JazzTeamServer/server/server.startup && tail -f /dev/null"]
#CMD ["/bin/bash"]
CMD top
