FROM registry.access.redhat.com/ubi8/ubi-init AS builder
Workdir /usr/ibm
RUN yum -y install wget unzip \
  && wget http://192.168.50.241:8081/download/ELM-Web.zip \
  && unzip ELM-Web.zip \
  && mkdir /usr/ibm/im/repo \
  && cd /usr/ibm \
  && wget http://192.168.50.241:8081/download/repo-auth.zip \
  && unzip *repo-auth* \
  && cd /usr/ibm/im/repo/jlip-auth-offering/offering-repo \
  && cp -Rf * ../../ \
  && cd /usr/ibm/im/linux.gtk.x86_64 \
  && ./installc -showVerboseProgress -input silent-install-jas2.xml --launcher.ini silent-install.ini -acceptLicense \
  && rm -rf /usr/ibm \
  && chown -R 1001:0 /opt/IBM

FROM registry.access.redhat.com/ubi8/ubi-init
WORKDIR /opt/IBM/JazzAuthServer
COPY --from=builder /opt/IBM/JazzAuthServer .
EXPOSE 9643
EXPOSE 9280
USER 1001
#CMD cp -aru /opt/IBM /elm && /elm/IBM/JazzTeamServer/server/server.startup && top
CMD sleep 100000
